import Head from "next/head";
import { Navbar } from "../components";
import { About, Footer, Header, Skills, Testimonial, Work } from "../container";
import { client } from "../client";

export default function Home({
  abouts,
  experiences,
  skills,
  testimonials,
  brands,
  works,
}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="app">
        <Navbar />
        {Header.getLayout(<Header />)}
        {About.getLayout(<About abouts={abouts} />)}
        {Work.getLayout(<Work works={works} />)}
        {Skills.getLayout(<Skills experiences={experiences} skills={skills} />)}
        {Testimonial.getLayout(
          <Testimonial brands={brands} testimonials={testimonials} />
        )}
        {Footer.getLayout(<Footer />)}
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const abouts = await client.fetch('*[_type == "abouts"]');
  const experiences = await client.fetch('*[_type == "experiences"]');
  const skills = await client.fetch('*[_type == "skills"]');
  const testimonials = await client.fetch('*[_type == "testimonials"]');
  const brands = await client.fetch('*[_type == "brands"]');
  const works = await client.fetch('*[_type == "works"]');

  return {
    props: {
      abouts,
      experiences,
      skills,
      testimonials,
      brands,
      works,
    },
  };
}
